### ISSUE TITLE
Use version-hash

### ISSUE THREAD

**Issue by stbischof** [osgi/jakartarest-osgi#3]
we have set all versions in ci actions to the version hashes but not skywark

https://github.com/osgi/jakartarest-osgi/blob/8c72bd9207da7dde0186ed7b9439d8c5dc020e15/.github/workflows/license.yml#L19
we should use the version hash also here.

https://github.com/apache/skywalking-eyes/commit/438e4ea5682269933ea2c8b5608662e52af26959

`438e4ea5682269933ea2c8b5608662e52af26959`

**Comment by maho7791** [comment]
Fixed for checkout-action and license-eye
