### ISSUE TITLE
Unused dependency in org.eclipse.osgitech.rest

### ISSUE THREAD

**Issue by glatuske** [osgi/jakartarest-osgi#43]
The pom.xml file of org.eclipse.osgitech.rest contains a non required/unused dependency to Apache Felix HTTP Jetty.

`<dependency>
   <groupId>org.apache.felix</groupId>
   <artifactId>org.apache.felix.http.jetty</artifactId>
</dependency>`

We figured that out when running SBOM Maven plugin on it. The OSGi bundles does not have a dependency to Jetty or Felix HTTP, but the SBOM Maven plugin detects this dependency,

**Comment by glatuske** [comment]
Thanks a lot!

**Comment by glatuske** [comment]
> This dependency is needed for integration tests.
> 
> https://github.com/osgi/jakartarest-osgi/blob/77199511b33d6d4e613cd2a895b7feebff1f52c5/org.eclipse.osgitech.rest.tests/test.bndrun#L22
> 
> We will update the scope.

But could it just moved to the test plugin? I think in the implementation it's not required?

**Comment by maho7791** [comment]
Sorry, the dependnecy is used to at compile scope in module:

org.eclipse.osgitech.rest.jetty

and for the tests

**Comment by maho7791** [comment]
Its not only used in one integration test bundle, but in multiples

**Comment by glatuske** [comment]
At least in org.eclipse.osgitech.rest itself it's not required ;-)

**Comment by maho7791** [comment]
Got it ;-)

**Comment by glatuske** [comment]
@maho7791 Would you create a release for this fix?
